version: '3.3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
     - POSTGRES_DB=${DB_DATABASE}
     - POSTGRES_USER=${DB_USERNAME}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
